### ISSUE TITLE
How are bboxes been extracted for EK dataset?

### ISSUE THREAD

**Issue by Randle-Github** [eladb3/ORViT#1]
I noticed that your README file didn't mention the preparation of Epic-Kitchens dataset and didn't see the pre-trained online detector part in your code. Feel confused about the method you process on this problem. Thank you!

**Comment by eladb3** [comment]
Hi, this is the folder containing the tracker code:
https://github.com/eladb3/ORViT/tree/master/slowfast/utils/LinkBoxes

For Epic-Kitchens, an H5 file containing the processed boxes should be created during the dataloader generation, assuming `cfg.EPICKITCHENS.VISUAL_DATA_DIR` contains the boxes provided here:
https://github.com/epic-kitchens/epic-kitchens-100-hand-object-bboxes

**Comment by Randle-Github** [comment]
Thank you!
