### ISSUE TITLE
where do I find bbox for something-somethingv2 dataset?

### ISSUE THREAD

**Issue by Jeba-create** [eladb3/ORViT#4]
When I execute the program with something-something v2 dataset, it is asking for the empty_bbox_val.json file, where do I find this file, please?..  

Thanks...

**Comment by eladb3** [comment]
Hi, please check out the instructions [here](https://github.com/eladb3/ORViT/blob/master/slowfast/datasets/DATASET.md), these files are in the dataset splits file.

Feel free to re-open this issue if you encounter any further issues.
