### ISSUE TITLE
Detection boxes for something-somethingv2 dataset

### ISSUE THREAD

**Issue by Jeba-create** [eladb3/ORViT#5]
I have found the detected bounding box for the something somethingv2 dataset here (https://drive.google.com/drive/folders/1XqZC2jIHqrLPugPOVJxCH_YWa275PBrZ). But they are stored in the split of 4 json files namely
bounding_box_smthsmth_part1.json
bounding_box_smthsmth_part2.json
bounding_box_smthsmth_part3.json
bounding_box_smthsmth_part4.json
Could you please help me are these the files I am required to give in the place of detected boxes?. If it is a different file, could you please provide the link to download the files? 

I guess the detection boxes have to be stored according to their filename. Because I got the error as
`No such file or directory: '../database/something-something/something-something-v2/detected_boxes/74225'`

 Is there any script to split the detected boxes of each file separately?

Thanks in advance

**Comment by eladb3** [comment]
Hi, please check out the instructions [here](https://github.com/eladb3/ORViT/blob/master/slowfast/datasets/DATASET.md), you can now download these boxes.

Feel free to re-open this issue if you encounter any further issues.
