### ISSUE TITLE
Problem about the bad baseline result

### ISSUE THREAD

**Issue by huangp0310** [eladb3/ORViT#6]
Hello, we run the baseline model on Something-else dataset under the ORViT framework. But the best acc we get is only **49.6**, which is far from the result (**60.2**) reported in the paper. There are no changes to the model's config file (`Smthelse_ORViT-MF_224_16x4.yaml`), except for the batch_size being adjusted to 16 (4 GPUs).

**Comment by eladb3** [comment]
Hi, this result is produced simply by training MF on the compositional split, the `Smthelse_ORViT-MF_224_16x4.yaml` config is for training MF~ORViT.

**Comment by yeyingdege** [comment]
> Hi, this result is produced simply by training MF on the compositional split, the `Smthelse_ORViT-MF_224_16x4.yaml` config is for training MF~ORViT.

Hello, I really appreciate your work. Could you please explain more about this issue? @eladb3
