### ISSUE TITLE
How to do inference on new video?

### ISSUE THREAD

**Issue by Jeba-create** [eladb3/ORViT#7]
If I do inference, it works on the validation set and it generates the prediction accuracy.  This is working fine, since we have the annotations for the validation set. But, for the test set or new input video, the detection has to be done before classification. Could you please help me with how to do inference for the new video where the detected bbox is unavailable?

Thanks in advance

**Comment by eladb3** [comment]
Hi,
You can use detector to extract boxes for your dataset. [Detectron2](https://github.com/facebookresearch/detectron2) is great.

**Comment by Jeba-create** [comment]
Thank you so much for your suggestion. I would like to know, Is the code available here to do detection on the fly or I would do detection, store the results and then follow the same procedure as for validation?

**Comment by eladb3** [comment]
Yes, you should store the detected bounding boxes, and then use them for ORViT

**Comment by Jeba-create** [comment]
One more suggestion please, Whether I should use  "get_boxes_gt" or "get_boxes_detected" in the ssv2.py script to process on "bbox" related stuff.
